# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Dimcirui

"""Float layouts of the constant buffers of RE6 materials. GENERATED by tools/make_shader_names.py from albam's
mrl.ksy (cb_globals_3 is the RE6 variant of $Globals). Field names without the f_ prefix; "" = padding.
"""

# buffer name hash (20 bit) -> (buffer name, [(field, float count)])
LAYOUTS = {
    0x7B2C2: ('$Globals', [
        ('albedo_color', 3),
        ('', 1),
        ('albedo_blend_color', 4),
        ('detail_normal_power', 1),
        ('detail_normal_uv_scale', 1),
        ('detail_normal2_power', 1),
        ('detail_normal2_uv_scale', 1),
        ('primary_shift', 1),
        ('secondary_shift', 1),
        ('parallax_factor', 1),
        ('parallax_self_occlusion', 1),
        ('parallax_min_sample', 1),
        ('parallax_max_sample', 1),
        ('', 2),
        ('light_map_color', 3),
        ('', 1),
        ('thin_map_color', 3),
        ('thin_scattering', 1),
        ('indirect_offset', 2),
        ('indirect_scale', 2),
        ('fresnel_schlick', 1),
        ('fresnel_schlick_rgb', 3),
        ('specular_color', 3),
        ('shininess', 1),
        ('emission_color', 3),
        ('alpha_clip_threshold', 1),
        ('primary_expo', 1),
        ('secondary_expo', 1),
        ('', 2),
        ('primary_color', 3),
        ('', 1),
        ('secondary_color', 3),
        ('', 1),
        ('albedo_color_2', 3),
        ('', 1),
        ('specular_color_2', 3),
        ('fresnel_schlick_2', 1),
        ('shininess_2', 1),
        ('', 3),
        ('transparency_clip_threshold', 4),
        ('blend_uv', 1),
        ('', 3),
        ('albedo_blend2_color', 4),
        ('detail_normalu_vscale', 2),
        ('', 2),
    ]),
    0x6C801: ('CBMaterial', [
        ('diffuse_color', 3),
        ('transparency', 1),
        ('reflective_color', 3),
        ('transparency_volume', 1),
        ('uv_transform', 8),
        ('uv_transform2', 8),
        ('uv_transform3', 8),
    ]),
    0x6F016: ('CBColorMask', [
        ('color_mask_threshold', 4),
        ('color_mask_offset', 4),
        ('clip_threshold', 4),
        ('color_mask_color', 4),
        ('color_mask2_threshold', 4),
        ('color_mask2_color', 4),
    ]),
    0x15419: ('CBVertexDisplacement', [
        ('vtx_disp_start', 1),
        ('vtx_disp_scale', 1),
        ('vtx_disp_inv_area', 1),
        ('vtx_disp_rcn', 1),
        ('vtx_disp_tilt_u', 1),
        ('vtx_disp_tilt_v', 1),
        ('', 2),
    ]),
    0x51814: ('CBVertexDisplacement2', [
        ('vtx_disp_start2', 1),
        ('vtx_disp_scale2', 1),
        ('vtx_disp_inv_area2', 1),
        ('vtx_disp_rcn2', 1),
    ]),
}


def layout_of(buffer_hash: int, count: int):
    """[(field, float count)] of a constant buffer when its layout is known and matches the number of floats"""
    e = LAYOUTS.get(buffer_hash >> 12 if buffer_hash > 0xFFFFF else buffer_hash)
    if e and sum(n for _, n in e[1]) == count:
        return e[1]
    return None
