# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Dimcirui

"""Bone function ids a chain (ctc) may be given, per character and part (no Blender dependency).

The ranges are generated by tools/pl_free_ids.py into chain_id_data.py (see docs/BONE_IDS.md): ids that no motion list (also the
cutscene / event ones), jex, link bone or kept bone of the model uses. GENERIC is the ids that are free in every model of the part
(the most conservative choice); the others are the ids of one character. Chain bones are numbered along the sorted list of the
free ids (gaps are skipped); an id outside the list, or too few free ids left, is refused (ChainIdError).
"""
from __future__ import annotations

from . import chain_id_data as D

# (identifier, label, data of D); the first one is the default
CHARACTERS = (('GENERIC', 'Generic (all characters)', D.GENERIC),
              ('ADA', 'Ada (Original Outfit)', D.ADA))
# (identifier, label, key in the data)
PARTS = (('BODY', 'Body (plXXz0)', 'body'),
         ('HEAD', 'Head (plXXz3)', 'head'))


class ChainIdError(ValueError):
    """kind: 'outside' (start id not allowed), 'empty' (nothing left), 'short' (not enough ids from the start id on)"""

    def __init__(self, kind, *args):
        super().__init__(kind, *args)
        self.kind = kind
        self.args_ = args


def parse_runs(text):
    out = []
    for part in text.split(','):
        if part:
            a, _, b = part.partition('-')
            out += range(int(a), int(b or a) + 1)
    return out


def format_runs(ids):
    out = []
    for i in sorted(ids):
        if out and i == out[-1][1] + 1:
            out[-1][1] = i
        else:
            out.append([i, i])
    return ', '.join(str(a) if a == b else '%d-%d' % (a, b) for a, b in out)


def label_of(items, ident):
    return next((l for i, l, _ in items if i == ident), ident)


def allowed_ids(character, part):
    """sorted ids the character may use for the part"""
    data = next(d for i, _, d in CHARACTERS if i == character)
    key = next(k for i, _, k in PARTS if i == part)
    return parse_runs(data[key])


def free_pool(character, part, used):
    """the allowed ids that no other bone of the armature uses, ascending"""
    return [i for i in allowed_ids(character, part) if i not in used]


def pick_ids(pool, start, count):
    """`count` ids along the pool beginning with `start`; ChainIdError when start is not in the pool or the pool runs out"""
    if not pool:
        raise ChainIdError('empty')
    if start not in pool:
        raise ChainIdError('outside', start)
    k = pool.index(start)
    ids = pool[k:k + count]
    if len(ids) < count:
        raise ChainIdError('short', count, len(ids), start)
    return ids


def suggest_start(pool, after, count):
    """first pool id >= `after` that still has `count` ids behind it (wrapping to the beginning); pool[0] / `after` when there is none"""
    if not pool:
        return after
    for k, i in enumerate(pool):
        if i >= after and len(pool) - k >= count:
            return i
    return pool[0]
