# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Dimcirui

# generated by tools/pl_free_ids.py (docs/BONE_IDS.md): bone function ids that no motion, jex or kept bone uses

GENERIC = {'body': '98-99,218-219,221-224,226,228-229,236-249',
           'head': '56-59,98-99,218-224,226,228-229,231,233-249'}
ADA = {'body': '56-57,77-99,123-129,135-189,213-249',
       'head': '56-59,77-99,123-129,135-189,213-249'}
