# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Dimcirui

"""Name hashes of the MT Framework resources, identical to the MHW Model Editor's.

* material name hash (the u32 in the .mod material table and in the .mrl material entry) = jamcrc32(name), i.e.
  ~crc32(name); verified on RE6 materials: 'pl_skin' = 0x68b3d093, 'pl_snow' = 0x5c491d3e, 'Null' = 0x7a06ac8e ...
* shader parameter hashes (texture slots, sampler states, constant buffers ...): the upper 20 bits are
  jamcrc32(name) & 0xFFFFF, the lower 12 bits are a code (the command header repeats them). The names come from
  shader_names.py (albam's table, generated by tools/make_shader_names.py).
"""
from __future__ import annotations

import zlib


def jamcrc32(name: str) -> int:
    # game names are ASCII (same bytes in utf-8); utf-8 also hashes Blender names with other characters (e.g. Chinese)
    return (zlib.crc32(name.encode('utf-8')) & 0xFFFFFFFF) ^ 0xFFFFFFFF


def name20(name: str) -> int:
    return jamcrc32(name) & 0xFFFFF


# material names that resolve: from the MHW dictionary (Null, Shadow, Material, pl_skin, pl_snow) and from guessing names
# out of the game's texture names (tools/hash_guess.py). The guess tried ~13 million names against 8331 hashes, so about
# 25 hits are expected by chance; only names with many uses (the player family pl_skin / pl_base / pl_cloth / pl_hair /
# pl_nuki / pl_eyeshadow with their numbered variants, the wp_Totan weapons) are kept, singletons were dropped
KNOWN_MATERIALS = (
    'pl_skin',
    'pl_skin1',
    'pl_skin2',
    'pl_skin3',
    'pl_base',
    'pl_base1',
    'pl_base2',
    'pl_base3',
    'pl_cloth',
    'pl_cloth1',
    'pl_cloth2',
    'pl_cloth3',
    'pl_hair',
    'pl_hair1',
    'pl_hair2',
    'pl_hair3',
    'pl_eyeshadow',
    'pl_nuki',
    'pl_nuki1',
    'pl_nuki2',
    'pl_nuki3',
    'pl_snow',
    'pl_snow1',
    'pl_snow2',
    'pl_glass',
    'shadow',
    'Shadow',
    'em1000_Shadow',
    'Null',
    'Material',
    'wp_Totan0021',
    'wp_Totan0022',
    'wp_Totan0023',
    'PL_Tutasmall_alpha',
)
MATERIAL_NAMES = {jamcrc32(n): n for n in KNOWN_MATERIALS}


def slot_name(h: int) -> str:
    """name of a sampler / texture slot or of any other shader parameter hash (tAlbedoMap, SSAlbedoMap, CBMaterial ...)"""
    from .shader_names import name_of
    return name_of(h)


# names learned while the editor runs (the Blender layer fills it from the scene and from the user's dictionary file,
# blender/material_names.py); the .mod has no name table, so this is where names of new materials come from
LEARNED = {}


def learn(name: str):
    """remember a material name; returns its hash (None for an empty name or MAT_<hash>)"""
    name = (name or '').strip()
    if not name or (name.startswith('MAT_') and len(name) == 12):
        return None
    h = jamcrc32(name)
    if h not in MATERIAL_NAMES:
        LEARNED[h] = name
    return h


def material_name(h: int) -> str:
    return MATERIAL_NAMES.get(h) or LEARNED.get(h, '')
